const express = require("express");
const router = express.Router();
const { query } = require("../config/postgres");
const uid = req => req.user && (req.user.id || req.user.uid || req.user.userId);

router.get("/profile", async (req,res,next)=>{try{const r=await query(`SELECT * FROM app.student_profiles WHERE user_id=$1`,[uid(req)]);res.json(r.rows[0]||null)}catch(e){next(e)}});
router.put("/profile", async (req,res,next)=>{try{const u=uid(req),b=req.body||{};const r=await query(`INSERT INTO app.student_profiles (user_id,college_id,department_id,program_id,academic_year_id,semester_id,roll_number,prn,current_year,branch,date_of_birth,gender,city,district,state,bio,headline,desired_role,experience_level,profile_visibility,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,COALESCE($20,public),now()) ON CONFLICT (user_id) DO UPDATE SET college_id=EXCLUDED.college_id,department_id=EXCLUDED.department_id,program_id=EXCLUDED.program_id,academic_year_id=EXCLUDED.academic_year_id,semester_id=EXCLUDED.semester_id,roll_number=EXCLUDED.roll_number,prn=EXCLUDED.prn,current_year=EXCLUDED.current_year,branch=EXCLUDED.branch,date_of_birth=EXCLUDED.date_of_birth,gender=EXCLUDED.gender,city=EXCLUDED.city,district=EXCLUDED.district,state=EXCLUDED.state,bio=EXCLUDED.bio,headline=EXCLUDED.headline,desired_role=EXCLUDED.desired_role,experience_level=EXCLUDED.experience_level,profile_visibility=EXCLUDED.profile_visibility,updated_at=now() RETURNING *`,[u,b.college_id||null,b.department_id||null,b.program_id||null,b.academic_year_id||null,b.semester_id||null,b.roll_number||null,b.prn||null,b.current_year||null,b.branch||null,b.date_of_birth||null,b.gender||null,b.city||null,b.district||null,b.state||null,b.bio||null,b.headline||null,b.desired_role||null,b.experience_level||null,b.profile_visibility||null]);res.json(r.rows[0])}catch(e){next(e)}});

router.get("/skills",async(req,res,next)=>{try{const r=await query(`SELECT s.*,ss.verified FROM app.student_skills ss JOIN app.skills s ON s.id=ss.skill_id JOIN app.student_profiles sp ON sp.id=ss.student_id WHERE sp.user_id=$1 ORDER BY s.name`,[uid(req)]);res.json(r.rows)}catch(e){next(e)}});
router.put("/skills",async(req,res,next)=>{try{const u=uid(req),skills=Array.isArray(req.body?.skills)?req.body.skills:[];const p=await query(`SELECT id FROM app.student_profiles WHERE user_id=$1`,[u]);if(!p.rowCount)return res.status(404).json({message:"Student profile not found."});await query("BEGIN");await query(`DELETE FROM app.student_skills WHERE student_id=$1`,[p.rows[0].id]);for(const x of skills){const id=x.id||x.skill_id;if(id)await query(`INSERT INTO app.student_skills(student_id,skill_id,verified) VALUES($1,$2,COALESCE($3,false)) ON CONFLICT DO NOTHING`,[p.rows[0].id,id,x.verified]);}await query("COMMIT");const r=await query(`SELECT s.*,ss.verified FROM app.student_skills ss JOIN app.skills s ON s.id=ss.skill_id WHERE ss.student_id=$1 ORDER BY s.name`,[p.rows[0].id]);res.json(r.rows)}catch(e){try{await query("ROLLBACK")}catch(_){}next(e)}});

router.get("/achievements",async(req,res,next)=>{try{const r=await query(`SELECT * FROM app.achievements WHERE user_id=$1 ORDER BY achievement_date DESC NULLS LAST,created_at DESC`,[uid(req)]);res.json(r.rows)}catch(e){next(e)}});
router.post("/achievements/award",async(req,res,next)=>{try{const b=req.body||{},r=await query(`INSERT INTO app.achievements(user_id,title,description,issuer,achievement_date,url) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[uid(req),b.title,b.description||null,b.issuer||null,b.achievement_date||null,b.url||null]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
router.delete("/achievements/:id",async(req,res,next)=>{try{const r=await query(`DELETE FROM app.achievements WHERE id=$1 AND user_id=$2 RETURNING *`,[req.params.id,uid(req)]);if(!r.rowCount)return res.status(404).json({message:"Achievement not found."});res.json({message:"Achievement deleted successfully."})}catch(e){next(e)}});

router.get("/goals",async(req,res,next)=>{try{const r=await query(`SELECT * FROM app.user_goals WHERE user_id=$1`,[uid(req)]);res.json(r.rows[0]||null)}catch(e){next(e)}});
router.put("/goals",async(req,res,next)=>{try{const b=req.body||{},r=await query(`INSERT INTO app.user_goals(user_id,weekly_goal,monthly_challenge,total_xp,daily_streak) VALUES($1,COALESCE($2,{}::jsonb),COALESCE($3,{}::jsonb),COALESCE($4,0),COALESCE($5,0)) ON CONFLICT(user_id) DO UPDATE SET weekly_goal=EXCLUDED.weekly_goal,monthly_challenge=EXCLUDED.monthly_challenge,total_xp=EXCLUDED.total_xp,daily_streak=EXCLUDED.daily_streak,updated_at=now() RETURNING *`,[uid(req),b.weekly_goal||{},b.monthly_challenge||{},b.total_xp||0,b.daily_streak||0]);res.json(r.rows[0])}catch(e){next(e)}});

router.get("/preferences",async(req,res,next)=>{try{const r=await query(`SELECT * FROM app.user_preferences WHERE user_id=$1`,[uid(req)]);res.json(r.rows[0]||null)}catch(e){next(e)}});
router.put("/preferences",async(req,res,next)=>{try{const b=req.body||{},r=await query(`INSERT INTO app.user_preferences(user_id,language,timezone,email_notifications,push_notifications,low_bandwidth_mode) VALUES($1,COALESCE($2,'en'),$3,COALESCE($4,true),COALESCE($5,true),COALESCE($6,false)) ON CONFLICT(user_id) DO UPDATE SET language=EXCLUDED.language,timezone=EXCLUDED.timezone,email_notifications=EXCLUDED.email_notifications,push_notifications=EXCLUDED.push_notifications,low_bandwidth_mode=EXCLUDED.low_bandwidth_mode,updated_at=now() RETURNING *`,[uid(req),b.language,b.timezone||null,b.email_notifications,b.push_notifications,b.low_bandwidth_mode]);res.json(r.rows[0])}catch(e){next(e)}});

module.exports=router;
