export const locationData = {
  India: {
    Maharashtra: {
      Pune: ["Haveli", "Pune City", "Mulshi", "Maval", "Khed", "Ambegaon", "Junnar", "Shirur", "Purandar", "Velhe", "Bhor", "Baramati", "Indapur", "Daund"],
      Mumbai: ["Mumbai City", "Mumbai Suburban", "Andheri", "Borivali", "Kurla", "Bandra", "Worli", "Colaba"],
      Thane: ["Thane", "Kalyan", "Bhiwandi", "Ulhasnagar", "Ambernath", "Shahapur", "Murbad"],
      Nagpur: ["Nagpur City", "Nagpur Rural", "Kamptee", "Hingna", "Katol", "Narkhed", "Savner", "Kalameshwar", "Ramtek", "Mouda", "Parseoni", "Umred", "Kuhi", "Bhiwapur"],
      Solapur: ["Solapur North", "Solapur South", "Barshi", "Akkalkot", "Pandharpur", "Mohol", "Mangalvedha", "Malshiras", "Sangola", "Karmala", "Madha"],
      Nashik: ["Nashik City", "Nashik Rural", "Nifad", "Dindori", "Igatpuri", "Trimbak", "Sinnar", "Chandwad", "Malegaon", "Baglan", "Kalwan", "Surgana", "Peint", "Yeola"],
      Aurangabad: ["Aurangabad City", "Aurangabad Rural", "Paithan", "Gangapur", "Vaijapur", "Kannad", "Sillod", "Soegaon", "Phulambri"],
      Kolhapur: ["Kolhapur City", "Karvir", "Panhala", "Hatkanangle", "Shirol", "Kagal", "Radhanagari", "Bavda", "Bhudargad", "Gaganbawada", "Shahuwadi", "Ajara", "Chandgad"],
      Satara: ["Satara City", "Koregaon", "Wai", "Mahabaleshwar", "Khandala", "Phaltan", "Khatav", "Man", "Jaoli", "Patan", "Karad"],
      Sangli: ["Miraj", "Sangli City", "Tasgaon", "Khanapur", "Atapadi", "Shirala", "Walwa", "Palus", "Kadegaon", "Kavthe Mahankal", "Jat"],
      Latur: ["Latur City", "Udgir", "Nilanga", "Ausa", "Deoni", "Renapur", "Shirur Anantpal", "Ahmedpur", "Chakur"],
      Nanded: ["Nanded City", "Ardhapur", "Dharmabad", "Hadgaon", "Bhokar", "Himayatnagar", "Kinwat", "Deglur", "Mukhed", "Kandhar", "Loha", "Naigaon", "Biloli", "Umri"],
      Osmanabad: ["Osmanabad City", "Tuljapur", "Lohara", "Omerga", "Kalamb", "Bhum", "Washi", "Paranda"],
      Ratnagiri: ["Ratnagiri City", "Dapoli", "Mandangad", "Guhagar", "Chiplun", "Sangameshwar", "Lanja", "Rajapur", "Khed"],
      Amravati: ["Amravati City", "Daryapur", "Anjangaon", "Warud", "Morshi", "Chandur Railway", "Achalpur", "Bhatkuli", "Nandgaon-Khandeshwar", "Chikhaldara", "Dharni", "Chikhaldhara"],
      Akola: ["Akola City", "Akot", "Balapur", "Patur", "Murtizapur", "Telhara", "Barshing"],
      Buldhana: ["Buldhana City", "Mehkar", "Lonar", "Sindhkhed Raja", "Motala", "Nandura", "Shegaon", "Malkapur", "Khamgaon", "Jalgaon Jamod", "Sangrampur", "Chikhli", "Deulgaon Raja"],
      Yavatmal: ["Yavatmal City", "Wani", "Ner", "Pusad", "Umarkhed", "Mahagaon", "Kelapur", "Ralegaon", "Ghatanji", "Babhulgaon", "Kalamb", "Darwha", "Digras", "Arni"],
      Wardha: ["Wardha City", "Seloo", "Deoli", "Hinganghat", "Samudrapur", "Arvi", "Karanja", "Ashti"],
      Jalgaon: ["Jalgaon City", "Amalner", "Erandol", "Chalisgaon", "Bhadgaon", "Pachora", "Jamner", "Dharangaon", "Bhusawal", "Muktainagar", "Yawal", "Raver", "Chopda", "Parola"],
      Dhule: ["Dhule City", "Shirpur", "Sakri", "Sindkheda"],
      Nandurbar: ["Nandurbar City", "Shahada", "Navapur", "Akkalkuwa", "Taloda", "Akrani"],
      Hingoli: ["Hingoli City", "Sengaon", "Kalamnuri", "Basmath", "Aundha Nagnath"],
      Parbhani: ["Parbhani City", "Selu", "Pathri", "Sonpeth", "Gangakhed", "Jintur", "Manwath", "Palum"],
      Beed: ["Beed City", "Georai", "Majalgaon", "Ashti", "Patoda", "Shirur Kasar", "Ambejogai", "Kaij", "Dharur", "Wadwani", "Parli"],
      Jalna: ["Jalna City", "Badnapur", "Bhokardan", "Jafrabad", "Partur", "Mantha", "Ambad", "Ghansawangi"],
      Raigad: ["Pen", "Alibag", "Murud", "Panvel", "Uran", "Karjat", "Khalapur", "Mangaon", "Tala", "Roha", "Sudhagad-Pali", "Mahad", "Poladpur", "Shrivardhan", "Mhasla"],
    },
    Karnataka: {
      Bengaluru: ["Bengaluru North", "Bengaluru South", "Bengaluru East", "Anekal", "Yelahanka"],
      Mysuru: ["Mysuru", "Hunsur", "Krishnarajanagara", "Periyapatna", "Heggadadevanakote", "Nanjangud", "Tirumakudalu Narasipura"],
      Hubballi: ["Hubballi City", "Dharwad", "Kalghatgi", "Navalgund", "Kundgol"],
      Belagavi: ["Belagavi City", "Gokak", "Sampagaon", "Khanapur", "Chikodi", "Nippani", "Raibag", "Athani", "Hukkeri", "Ramdurg", "Bailhongal"],
      Kalaburagi: ["Kalaburagi City", "Afzalpur", "Aland", "Chincholi", "Chittapur", "Jewargi", "Sedam"],
      Mangaluru: ["Mangaluru City", "Bantwal", "Sullia", "Belthangady", "Puttur", "Kadaba"],
    },
    "Andhra Pradesh": {
      Visakhapatnam: ["Visakhapatnam City", "Bheemunipatnam", "Anakapalle", "Chodavaram", "Narsipatnam", "Paderu", "Araku Valley", "Yellamanchili"],
      Vijayawada: ["Vijayawada City", "Machilipatnam", "Gannavaram", "Nandigama", "Jaggayyapeta", "Tiruvur", "Nuzvid", "Chandarlapadu"],
      Guntur: ["Guntur City", "Narasaraopet", "Tenali", "Repalle", "Bapatla", "Chirala", "Ongole", "Markapur"],
      Tirupati: ["Tirupati City", "Srikalahasti", "Puttur", "Nagari", "Gudur", "Sullurupeta"],
    },
    "Tamil Nadu": {
      Chennai: ["Chennai North", "Chennai South", "Chennai East", "Tambaram", "Sholinganallur", "Ambattur"],
      Coimbatore: ["Coimbatore North", "Coimbatore South", "Mettupalayam", "Pollachi", "Anaimalai", "Valparai"],
      Madurai: ["Madurai North", "Madurai South", "Melur", "Thirumangalam", "Usilampatti", "Peraiyur"],
      Salem: ["Salem City", "Attur", "Edapadi", "Omalur", "Yercaud", "Mettur", "Gangavalli"],
    },
    Delhi: {
      "New Delhi": ["Connaught Place", "Parliament Street", "Chanakyapuri"],
      "South Delhi": ["Hauz Khas", "Mehrauli", "Saket", "Kalkaji", "Greater Kailash", "Lajpat Nagar"],
      "North Delhi": ["Civil Lines", "Kotwali", "Sadar Bazar", "Rohini", "Pitampura"],
      "East Delhi": ["Preet Vihar", "Patparganj", "Vivek Vihar", "Geeta Colony"],
      "West Delhi": ["Rajouri Garden", "Punjabi Bagh", "Paschim Vihar", "Janakpuri"],
    },
    Gujarat: {
      Ahmedabad: ["Ahmedabad City", "Daskroi", "Sanand", "Bavla", "Dholka", "Viramgam", "Mandal", "Detroj-Rampura", "Dhandhuka"],
      Surat: ["Surat City", "Choryasi", "Olpad", "Kamrej", "Mangrol", "Mandvi", "Umarpada", "Bardoli", "Mahuva"],
      Vadodara: ["Vadodara City", "Padra", "Karjan", "Savli", "Vaghodia", "Desar"],
      Rajkot: ["Rajkot City", "Kotda Sangani", "Lodhika", "Gondal", "Jetpur", "Dhoraji", "Jamkandorana", "Upleta"],
    },
    Telangana: {
      Hyderabad: ["Hyderabad City", "Secunderabad", "LB Nagar", "Kukatpally", "Serilingampally", "Rajendranagar"],
      Warangal: ["Warangal City", "Hanamkonda", "Parkal", "Narsampet", "Mahabubabad"],
      Nizamabad: ["Nizamabad City", "Armoor", "Bodhan", "Kotagiri", "Balkonda", "Bheemgal"],
    },
    "Uttar Pradesh": {
      Lucknow: ["Lucknow City", "Mohanlalganj", "Bakshi Ka Talab", "Sarojini Nagar", "Malihabad", "Gosainganj"],
      Kanpur: ["Kanpur City", "Kanpur Rural", "Ghatampur", "Bilhaur", "Bhognipur", "Akbarpur", "Sishamau"],
      Agra: ["Agra City", "Agra Rural", "Fatehabad", "Kheragarh", "Fatehpur Sikri", "Barauli Ahir", "Saiyan", "Etmadpur"],
      Varanasi: ["Varanasi City", "Sewapuri", "Pindra", "Harahuwa", "Arajiline", "Cholapur"],
    },
    "Madhya Pradesh": {
      Bhopal: ["Bhopal City", "Huzur", "Berasia", "Phanda"],
      Indore: ["Indore City", "Depalpur", "Sanwer", "Hatod", "Manpur", "Mhow"],
      Gwalior: ["Gwalior City", "Morar", "Gwalior Rural", "Bhitarwar", "Dabra"],
      Jabalpur: ["Jabalpur City", "Sihora", "Shahpura", "Patan", "Kundam", "Katangi", "Badwara", "Panagar"],
    },
    Rajasthan: {
      Jaipur: ["Jaipur City", "Jaipur Rural", "Amber", "Kotputli", "Shahpura", "Sanganer", "Bassi"],
      Jodhpur: ["Jodhpur City", "Jodhpur Rural", "Bilara", "Osian", "Shergarh", "Lohawat", "Bhopalgarh"],
      Udaipur: ["Udaipur City", "Mavli", "Vallabhnagar", "Salumbar", "Kherwara", "Girwa", "Gogunda", "Lasadiya"],
      Kota: ["Kota City", "Ladpura", "Sangod", "Pipalda", "Sultanpur", "Ramganj Mandi"],
    },
    Punjab: {
      Ludhiana: ["Ludhiana City", "Khanna", "Samrala", "Payal", "Dehlon", "Machhiwara", "Raikot"],
      Amritsar: ["Amritsar City", "Ajnala", "Baba Bakala", "Attari", "Majitha"],
      Jalandhar: ["Jalandhar City", "Nakodar", "Phillaur", "Shahkot", "Kartarpur"],
    },
    "West Bengal": {
      Kolkata: ["Kolkata City", "Garden Reach", "Jorasanko", "Entally", "Beliaghata"],
      Howrah: ["Howrah City", "Uluberia", "Amta", "Udaynarayanpur", "Bagnan"],
      Darjeeling: ["Darjeeling City", "Siliguri", "Mirik", "Kurseong", "Kalimpong"],
    },
  }
};
