export const MAHARASHTRA_COLLEGES = [
  "Indian Institute of Technology (IIT), Bombay",
  "College of Engineering Pune (COEP)",
  "Visvesvaraya National Institute of Technology (VNIT), Nagpur",
  "Veermata Jijabai Technological Institute (VJTI), Mumbai",
  "Pune Institute of Computer Technology (PICT), Pune",
  "Sardar Patel Institute of Technology (SPIT), Mumbai",
  "Walchand College of Engineering, Sangli",
  "Dwarkadas J. Sanghvi College of Engineering (DJSCE), Mumbai",
  "K. J. Somaiya College of Engineering, Mumbai",
  "Vishwakarma Institute of Technology (VIT), Pune",
  "Shri Ramdeobaba College of Engineering and Management (RCOEM), Nagpur",
  "Government College of Engineering, Amravati",
  "Government College of Engineering, Aurangabad",
  "Government College of Engineering, Karad",
  "Government College of Engineering, Jalgaon",
  "Government College of Engineering, Nagpur",
  "Government College of Engineering, Chandrapur",
  "Thakur College of Engineering and Technology (TCET), Mumbai",
  "Fr. Conceicao Rodrigues College of Engineering (FRCRCE), Mumbai",
  "Thadomal Shahani Engineering College (TSEC), Mumbai",
  "Pimpri Chinchwad College of Engineering (PCCOE), Pune",
  "Cummins College of Engineering for Women, Pune",
  "Army Institute of Technology (AIT), Pune",
  "MIT World Peace University (MIT-WPU), Pune",
  "Bharati Vidyapeeth Deemed University College of Engineering, Pune",
  "SVERI College of Engineering, Pandharpur",
  "Sinhgad College of Engineering (SCOE), Pune",
  "Rajarshi Shahu College of Engineering (RSCOE), Pune",
  "D. Y. Patil College of Engineering, Akurdi, Pune",
  "Symbiosis Institute of Technology (SIT), Pune",
  "Don Bosco Institute of Technology (DBIT), Mumbai",
  "Vidyalankar Institute of Technology (VIT), Mumbai",
  "Rajiv Gandhi Institute of Technology (RGIT), Mumbai",
  "Mukesh Patel School of Technology Management & Engineering, Mumbai",
  "Sanjivani College of Engineering, Kopargaon",
  "K. K. Wagh Institute of Engineering Education & Research, Nashik",
  "G. H. Raisoni College of Engineering (GHRCE), Nagpur",
  "Yeshwantrao Chavan College of Engineering (YCCE), Nagpur",
  "Sipna College of Engineering and Technology, Amravati",
  "Prof. Ram Meghe Institute of Technology and Research, Amravati",
  "P. R. Pote Patil College of Engineering and Management, Amravati",
  "Anuradha Engineering College, Chikhli",
  "Shri Sant Gajanan Maharaj College of Engineering (SSGMCE), Shegaon",
  "Jawaharlal Darda Institute of Engineering and Technology, Yavatmal",
  "B. R. Harne College of Engineering and Technology, Ambernath",
  "Rizvi College of Engineering, Mumbai",
  "Saraswati College of Engineering, Kharghar",
  "Terna Engineering College, Nerul",
  "SIES Graduate School of Technology, Nerul",
  "Fr. C. Rodrigues Institute of Technology, Vashi",
  "Dr. D. Y. Patil Ramrao Adik Institute of Technology (RAIT), Nerul",
  "K.J. Somaiya Institute of Engineering and Information Technology (KJSIEIT), Sion",
  "Shah and Anchor Kutchhi Engineering College (SAKEC), Mumbai",
  "M.H. Saboo Siddik College of Engineering, Mumbai",
  "Atharva College of Engineering, Mumbai",
  "St. Francis Institute of Technology (SFIT), Mumbai",
  "Xavier Institute of Engineering, Mumbai"
];
