export const MAHARASHTRA_COLLEGES = [
  // IIT, NIT, IIIT, Government
  "Indian Institute of Technology (IIT), Bombay",
  "Visvesvaraya National Institute of Technology (VNIT), Nagpur",
  "Indian Institute of Information Technology (IIIT), Pune",
  "Indian Institute of Information Technology (IIIT), Nagpur",
  "College of Engineering Pune (COEP Technological University)",
  "Veermata Jijabai Technological Institute (VJTI), Mumbai",
  "Institute of Chemical Technology (ICT), Mumbai",
  "Government College of Engineering, Amravati",
  "Government College of Engineering, Aurangabad",
  "Government College of Engineering, Karad",
  "Government College of Engineering, Jalgaon",
  "Government College of Engineering, Nagpur",
  "Government College of Engineering, Chandrapur",
  "Government College of Engineering, Yavatmal",
  "Government College of Engineering and Research, Avasari",
  "Shri Guru Gobind Singhji Institute of Engineering and Technology (SGGSIET), Nanded",
  "Walchand College of Engineering, Sangli",
  "Dr. Babasaheb Ambedkar Technological University (DBATU), Lonere",

  // Pune Region (SPPU)
  "Pune Institute of Computer Technology (PICT), Pune",
  "Vishwakarma Institute of Technology (VIT), Pune",
  "Pimpri Chinchwad College of Engineering (PCCOE), Pune",
  "Pimpri Chinchwad College of Engineering and Research (PCCOER), Ravet",
  "Cummins College of Engineering for Women, Pune",
  "Army Institute of Technology (AIT), Pune",
  "MIT World Peace University (MIT-WPU), Pune",
  "MIT Academy of Engineering (MITAOE), Alandi",
  "Bharati Vidyapeeth Deemed University College of Engineering, Pune",
  "Sinhgad College of Engineering (SCOE), Vadgaon, Pune",
  "Smt. Kashibai Navale College of Engineering, Pune",
  "NBN Sinhgad Technical Institutes Campus, Pune",
  "RMD Sinhgad School of Engineering, Warje, Pune",
  "SKN Sinhgad Institute of Technology and Science, Lonavala",
  "Rajarshi Shahu College of Engineering (RSCOE), Tathawade, Pune",
  "D. Y. Patil College of Engineering, Akurdi, Pune",
  "Dr. D. Y. Patil Institute of Technology, Pimpri, Pune",
  "Dr. D. Y. Patil Institute of Engineering, Management and Research (DYPIEMR), Akurdi",
  "Symbiosis Institute of Technology (SIT), Pune",
  "AISSMS College of Engineering, Pune",
  "AISSMS Institute of Information Technology, Pune",
  "PES Modern College of Engineering, Pune",
  "P.V.G.'s College of Engineering and Technology, Pune",
  "Jayawantrao Sawant College of Engineering, Hadapsar, Pune",
  "Zeal College of Engineering and Research, Narhe, Pune",
  "Trinity Academy of Engineering, Pune",
  "Trinity College of Engineering and Research, Pune",
  "KJ College of Engineering and Management Research, Pune",
  "Indira College of Engineering and Management, Pune",
  "Alard College of Engineering and Management, Pune",
  "Genba Sopanrao Moze College of Engineering, Balewadi, Pune",
  "Marathwada Mitra Mandal's College of Engineering (MMCOE), Karvenagar, Pune",
  "Marathwada Mitra Mandal's Institute of Technology (MMIT), Lohgaon",
  "Dhole Patil College of Engineering, Wagholi, Pune",
  "Anantrao Pawar College of Engineering & Research, Pune",
  "Vidya Pratishthan's Kamalnayan Bajaj Institute of Engineering and Technology, Baramati",
  "Sanjivani College of Engineering, Kopargaon",
  "Amrutvahini College of Engineering, Sangamner",
  "Pravara Rural Engineering College, Loni",
  "SND College of Engineering & Research Center, Yeola",
  
  // Mumbai & Navi Mumbai Region (MU)
  "Sardar Patel Institute of Technology (SPIT), Mumbai",
  "Sardar Patel College of Engineering (SPCE), Mumbai",
  "Dwarkadas J. Sanghvi College of Engineering (DJSCE), Mumbai",
  "K. J. Somaiya College of Engineering, Vidyavihar, Mumbai",
  "K. J. Somaiya Institute of Engineering and Information Technology (KJSIEIT), Sion",
  "Thakur College of Engineering and Technology (TCET), Kandivali, Mumbai",
  "Fr. Conceicao Rodrigues College of Engineering (FRCRCE), Bandra, Mumbai",
  "Thadomal Shahani Engineering College (TSEC), Bandra, Mumbai",
  "Don Bosco Institute of Technology (DBIT), Kurla, Mumbai",
  "Vidyalankar Institute of Technology (VIT), Wadala, Mumbai",
  "Rajiv Gandhi Institute of Technology (RGIT), Andheri, Mumbai",
  "Mukesh Patel School of Technology Management & Engineering (NMIMS), Mumbai",
  "Rizvi College of Engineering, Bandra, Mumbai",
  "M.H. Saboo Siddik College of Engineering, Byculla, Mumbai",
  "Atharva College of Engineering, Malad, Mumbai",
  "St. Francis Institute of Technology (SFIT), Borivali, Mumbai",
  "Xavier Institute of Engineering, Mahim, Mumbai",
  "Shah and Anchor Kutchhi Engineering College (SAKEC), Chembur, Mumbai",
  "Vivekanand Education Society's Institute of Technology (VESIT), Chembur",
  "Fr. C. Rodrigues Institute of Technology (FCRIT), Vashi, Navi Mumbai",
  "Dr. D. Y. Patil Ramrao Adik Institute of Technology (RAIT), Nerul, Navi Mumbai",
  "SIES Graduate School of Technology, Nerul, Navi Mumbai",
  "Terna Engineering College, Nerul, Navi Mumbai",
  "Saraswati College of Engineering, Kharghar, Navi Mumbai",
  "Lokmanya Tilak College of Engineering, Koparkhairane, Navi Mumbai",
  "A. C. Patil College of Engineering, Kharghar, Navi Mumbai",
  "Pillai College of Engineering, New Panvel",
  "Mahatma Gandhi Mission's College of Engineering and Technology, Kamothe",
  "Datta Meghe College of Engineering, Airoli, Navi Mumbai",
  "B. R. Harne College of Engineering and Technology, Ambernath",
  "Universal College of Engineering, Vasai",
  "VIVA Institute of Technology, Virar",
  "Theem College of Engineering, Boisar",
  "Ideal Institute of Technology, Wada",

  // Nagpur & Amravati Region (Vidarbha)
  "Shri Ramdeobaba College of Engineering and Management (RCOEM), Nagpur",
  "G. H. Raisoni College of Engineering (GHRCE), Nagpur",
  "G. H. Raisoni Institute of Engineering and Technology, Nagpur",
  "Yeshwantrao Chavan College of Engineering (YCCE), Nagpur",
  "St. Vincent Pallotti College of Engineering and Technology, Nagpur",
  "K.D.K. College of Engineering, Nagpur",
  "Priyadarshini College of Engineering, Nagpur",
  "S.B. Jain Institute of Technology, Management and Research, Nagpur",
  "Jhulelal Institute of Technology, Nagpur",
  "Tulsiramji Gaikwad-Patil College of Engineering and Technology, Nagpur",
  "Sipna College of Engineering and Technology, Amravati",
  "Prof. Ram Meghe Institute of Technology and Research, Badnera, Amravati",
  "Prof. Ram Meghe College of Engineering and Management, Badnera",
  "P. R. Pote Patil College of Engineering and Management, Amravati",
  "Shri Sant Gajanan Maharaj College of Engineering (SSGMCE), Shegaon",
  "Jawaharlal Darda Institute of Engineering and Technology, Yavatmal",
  "Anuradha Engineering College, Chikhli",
  "Bapurao Deshmukh College of Engineering, Sevagram, Wardha",
  "Rajiv Gandhi College of Engineering and Research, Nagpur",
  "Guru Nanak Institute of Engineering and Technology, Nagpur",

  // Nashik Region
  "K. K. Wagh Institute of Engineering Education & Research, Nashik",
  "NDMVP Samaj's Karmaveer Adv. Baburao Ganpatrao Thakare College of Engineering (KBTCOE), Nashik",
  "Sandip Institute of Technology and Research Centre (SITRC), Nashik",
  "Sandip Institute of Engineering and Management (SIEM), Nashik",
  "MET's Institute of Engineering, Bhujbal Knowledge City, Nashik",
  "Guru Gobind Singh College of Engineering and Research Centre, Nashik",
  "Gokhale Education Society's R. H. Sapat College of Engineering, Nashik",
  "SNJB's Late Sau. Kantabai Bhavarlalji Jain College of Engineering, Chandwad",
  "Shatabdi Institute of Engineering and Research, Nashik",
  
  // Aurangabad & Nanded Region (Marathwada)
  "Deogiri Institute of Engineering and Management Studies (DIEMS), Aurangabad",
  "Jawaharlal Nehru Engineering College (JNEC), Aurangabad",
  "Marathwada Institute of Technology (MIT), Aurangabad",
  "Maharashtra Institute of Technology, Aurangabad",
  "Everest Educational Society's Group of Institutions, Aurangabad",
  "Shreeyash College of Engineering and Technology, Aurangabad",
  "MGM's College of Engineering, Nanded",
  "Matoshri Pratishthan Group of Institutions, Nanded",
  "M.S. Bidve Engineering College, Latur",
  "VDF School of Engineering & Technology, Latur",
  "Aditya Engineering College, Beed",
  
  // Kolhapur, Sangli, Satara, Solapur Region (Western Maharashtra)
  "K.I.T.'s College of Engineering, Kolhapur",
  "D. Y. Patil College of Engineering and Technology, Kolhapur",
  "Sanjeevan Engineering and Technology Institute (SETI), Panhala, Kolhapur",
  "Tatyasaheb Kore Institute of Engineering and Technology, Warananagar",
  "Annasaheb Dange College of Engineering and Technology, Ashta, Sangli",
  "Rajarambapu Institute of Technology (RIT), Sakharale, Sangli",
  "Karmayogi Engineering College, Pandharpur",
  "SVERI College of Engineering, Pandharpur",
  "Nagesh Karajagi Orchid College of Engineering and Technology, Solapur",
  "Walchand Institute of Technology (WIT), Solapur",
  "Bramhadevdada Mane Institute of Technology, Solapur",
  "A. G. Patil Institute of Technology, Solapur",
  "Satara College of Engineering and Management, Satara",
  "Karmaveer Bhaurao Patil College of Engineering, Satara",
  "Phaltan Education Society's College of Engineering, Phaltan",
  "D.K.T.E. Society's Textile and Engineering Institute, Ichalkaranji",
  "Sharad Institute of Technology College of Engineering, Yadrav",
  
  // Khandesh Region (Jalgaon, Dhule, Nandurbar)
  "SSBT's College of Engineering and Technology, Bambhori, Jalgaon",
  "G. H. Raisoni Institute of Engineering and Management, Jalgaon",
  "K. C. E. Society's College of Engineering and Information Technology, Jalgaon",
  "Shri Vile Parle Kelavani Mandal's Institute of Technology (SVKM), Dhule",
  "R. C. Patel Institute of Technology, Shirpur",
  "Gangamai College of Engineering, Nagaon, Dhule",
  
  // Other Degree Colleges and Institutes (B.Sc, BCA, etc.)
  "Fergusson College, Pune",
  "Sir Parashurambhau (SP) College, Pune",
  "Brihan Maharashtra College of Commerce (BMCC), Pune",
  "Nowrosjee Wadia College, Pune",
  "St. Xavier's College, Mumbai",
  "Mithibai College, Mumbai",
  "Narsee Monjee College of Commerce and Economics, Mumbai",
  "H.R. College of Commerce and Economics, Mumbai",
  "Jai Hind College, Mumbai",
  "K. C. College, Mumbai",
  "Ruia College, Mumbai",
  "Ruparel College, Mumbai",
  "V.G. Vaze College of Arts, Science and Commerce, Mulund",
  "Bhavan's College, Andheri",
  "S. K. Somaiya Degree College of Arts, Science and Commerce, Vidyavihar",
  "Sydenham College of Commerce and Economics, Mumbai",
  "Elphinstone College, Mumbai",
  "Government Institute of Science, Nagpur",
  "Hislop College, Nagpur",
  "G. S. College of Commerce and Economics, Nagpur",
  "S.F.S. College, Nagpur",
  "Brijlal Biyani Science College, Amravati",
  "Vidya Bharati Mahavidyalaya, Amravati",
  "Deogiri College, Aurangabad",
  "Maulana Azad College of Arts, Science and Commerce, Aurangabad",
  "K.T.H.M. College, Nashik",
  "B.Y.K. College of Commerce, Nashik",
  "Vivekanand College, Kolhapur",
  "Chhatrapati Shahu Institute of Business Education and Research (CSIBER), Kolhapur",
  "Sangameshwar College, Solapur",
  "Dayanand College of Arts and Science, Solapur",
  "Moolji Jaitha College, Jalgaon"
];
